Support recurring events
CS2103AUG2016-W11-C2/main pull request #106
Opened 2016-10-24 06:53 UTC by fanwgwg

Going to add more testcases

2016-10-25 18:23 UTC, burnflare commented
LOL
> On 24 Oct 2016, at 7:49 PM, Coveralls <notifications@github.com> wrote:
> 
>  <https://coveralls.io/builds/8475141>
> Coverage decreased (-4.9%) to 78.728% when pulling 5125320 <https://github.com/CS2103AUG2016-W11-C2/main/commit/512532087a60a6629fad763eeec2b75d4928aeb9> on support-recurring-events into 6ea4e73 <https://github.com/CS2103AUG2016-W11-C2/main/commit/6ea4e73d215bea951f2634567e4a82cc45564df8> on master.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub <https://github.com/CS2103AUG2016-W11-C2/main/pull/106#issuecomment-255718895>, or mute the thread <https://github.com/notifications/unsubscribe-auth/AAGW1lQ9jmeHEL0esi-p_SQo6hvY6Bqtks5q3JsugaJpZM4Kecw_>.
>

2016-10-26 01:38 UTC, burnflare commented
@fanwgwg Do fix the conflicts with master

2016-10-26 10:41 UTC, burnflare commented
@fanwgwg Are you ready to merge this?

2016-10-26 10:51 UTC, fanwgwg commented
@burnflare yup can merge, I'll just resolve the conflicts first

2016-10-26 10:51 UTC, INCENDE commented
Btw weiguang are you applying the abstraction occurrence pattern?

2016-10-26 10:53 UTC, fanwgwg commented
@INCENDE  yup I followed the pattern!

2016-10-26 10:58 UTC, INCENDE commented on src/main/java/seedu/agendum/model/task/ChildRecurringTask.java
> +public class ChildRecurringTask extends RecurringTask {
I believe in the abstraction occurrence pattern, the occurence should not extend the abstraction

2016-10-26 10:59 UTC, INCENDE commented on src/main/java/seedu/agendum/model/task/ChildRecurringTask.java
> +public class ChildRecurringTask extends RecurringTask {
"The _Abstraction_ class should hold all common information, and the unique information
should be kept by the _Occurrence_ class" 
In damith's handout

2016-10-26 11:03 UTC, fanwgwg commented on src/main/java/seedu/agendum/model/task/ChildRecurringTask.java
> +public class ChildRecurringTask extends RecurringTask {
Yup it does say so on the handouts, but it never says the relationship between these two classes. In my implementation, RecurringTask stores the general information, childRecurringTask stores the unque information, I think it still follows the abstraction-occurrence pattern.

2016-10-27 15:19 UTC, rachx requested changes
Putting this on hold as I haven't read it thoroughly yet.
Can you explain the high level design e.g. how the model class diagram will change etc? (If not on github, then offline)

2016-10-27 15:48 UTC, fanwgwg commented
@rachx  just updated the model class diagram

2016-10-29 03:22 UTC, rachx commented
1) Should the creation of new occurrence be tied to mark?
1.1) Then what about unmarking? They should able to unmark as well.
2) How to delete an occurrence vs how to delete a recurrence? Is there a limit to the recurrence e.g. within a year?
3) can purposely add tasks (recurring or not) with the same properties as an existing recurring one.
4) now if i try to mark a recurring task occurrence multiple times, the new one will appear many times
5) how about if google calendar integration is successful, pull from there instead

2016-10-29 06:04 UTC, fanwgwg commented
1. Of course this would be easier for users, otherwise how can the next task appear if the previous task hasn't bee completed yet?
1.1. These tasks are able to mark. But my idea is that, for example, if I have a recurring task to do every month, if I've already marked the Aug one, the Sep one, I can only unmark the latest one, which is the Sep one, instead of the Aug one, because it doesn't make sense to unmark the previous recurring task, and I will prompt to the user that "future tasks have been marked". If the latest occurence is unmarked, then all the previous occurence will go back one period, as well as the recurrence.
2. In my desigan, all occurence are completed, but the recurrence is never completed, because once the recurrence is marked, I will create new occurence of the same due time as the recurrence, and update the time of the recurrence to next recurring time. So delete a occurence, then it's just deleted, and it doesn't affect anything. If delete a recurrence, the recurring event is deleted, besides those occurrences that already marked.
3. This one I'll look into it.
5. Of course it should appear many times, because once you mark, its time will change, and all the appearred occurence are of different time. For example, you `add homework every day`, if you mark it once, time of this task will be changed to 31,Oct, and there will be a new task appearing in the completed task panel, which is 30,Oct. If you mark one more time, the recurrence will have time 1,Nov, and there will be one more occurence in the completed task panel, with time being 31, Oct.

Hope that makes sense.

2016-11-04 13:01 UTC, burnflare commented
@rachx Are we dropping this?

2016-11-04 15:24 UTC, rachx commented
Yes. Weiguang agreed

---- Vishnu Prem wrote ----


@rachx<https://github.com/rachx> Are we dropping this?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/CS2103AUG2016-W11-C2/main/pull/106#issuecomment-258424936>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AP35PAEcBvbM7jSQWsDdaHUITt_ShlMOks5q6yzCgaJpZM4Kecw_>.

2016-11-05 01:32 UTC, closed without merging